#Date: 11/11/2016
#Class: CS4310
#Assignment: Assignment 7
#Author(s): Alex Dekau

tester :
	python tester.py

tests :
	python test_directed.py
	python test_adjacency.py
	python test_eremoval.py
	python test_vremoval.py
	python test_adjrem.py
	python test_degree.py

dir :
	python test_directed.py

adj :
	python test_adjacency.py

erem :
	python test_eremoval.py

vrem :
	python test_vremoval.py

arem :
	python test_adjrem.py

deg :
	python test_degree.py

clean :
	rm *.pyc
